/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LTORegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "admin" | "getRoot" | "issueLicense" | "revokeLicense"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LicenseIssued" | "LicenseRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "getRoot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "issueLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeLicense",
    values: [BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeLicense",
    data: BytesLike
  ): Result;
}

export namespace LicenseIssuedEvent {
  export type InputTuple = [
    executor: AddressLike,
    leafCommitment: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    leafCommitment: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    executor: string;
    leafCommitment: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseRevokedEvent {
  export type InputTuple = [
    executor: AddressLike,
    index: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    index: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    executor: string;
    index: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LTORegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LTORegistry;
  waitForDeployment(): Promise<this>;

  interface: LTORegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getRoot: TypedContractMethod<[], [bigint], "view">;

  issueLicense: TypedContractMethod<
    [leafCommitment: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeLicense: TypedContractMethod<
    [index: BigNumberish, siblings: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "issueLicense"
  ): TypedContractMethod<[leafCommitment: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeLicense"
  ): TypedContractMethod<
    [index: BigNumberish, siblings: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LicenseIssued"
  ): TypedContractEvent<
    LicenseIssuedEvent.InputTuple,
    LicenseIssuedEvent.OutputTuple,
    LicenseIssuedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseRevoked"
  ): TypedContractEvent<
    LicenseRevokedEvent.InputTuple,
    LicenseRevokedEvent.OutputTuple,
    LicenseRevokedEvent.OutputObject
  >;

  filters: {
    "LicenseIssued(address,uint256,uint256)": TypedContractEvent<
      LicenseIssuedEvent.InputTuple,
      LicenseIssuedEvent.OutputTuple,
      LicenseIssuedEvent.OutputObject
    >;
    LicenseIssued: TypedContractEvent<
      LicenseIssuedEvent.InputTuple,
      LicenseIssuedEvent.OutputTuple,
      LicenseIssuedEvent.OutputObject
    >;

    "LicenseRevoked(address,uint256,uint256)": TypedContractEvent<
      LicenseRevokedEvent.InputTuple,
      LicenseRevokedEvent.OutputTuple,
      LicenseRevokedEvent.OutputObject
    >;
    LicenseRevoked: TypedContractEvent<
      LicenseRevokedEvent.InputTuple,
      LicenseRevokedEvent.OutputTuple,
      LicenseRevokedEvent.OutputObject
    >;
  };
}
