// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract LTORegistry {
    address public admin;
    
    // The exact Poseidon2 Root generated by your frontend
    uint256 public currentRoot; 
    
    // The Private Chain Database (Stores every single driver directly on-chain)
    uint256[] public driverLeaves;

    event LicenseIssued(address indexed executor, uint256 indexed leafCommitment, uint256 newRoot, uint256 timestamp);
    event LicenseRevoked(address indexed executor, uint256 indexed index, uint256 newRoot, uint256 timestamp);

    modifier onlyAdmin() {
        require(msg.sender == admin, "Only LTO Admin allowed");
        _;
    }

    constructor() {
        admin = msg.sender;
    }

    // Frontend does the Poseidon2 math, sends the Leaf AND the New Root here
    function Active(uint256 leafCommitment, uint256 newRoot) public onlyAdmin {
        driverLeaves.push(leafCommitment);
        currentRoot = newRoot; 
        
        emit LicenseIssued(msg.sender, leafCommitment, newRoot, block.timestamp);
    }

    // Frontend calculates the new tree after revoking, sends the New Root here
    function Revoke(uint256 index, uint256 newRoot) public onlyAdmin {
        driverLeaves[index] = 0;
        currentRoot = newRoot; 
        
        emit LicenseRevoked(msg.sender, index, newRoot, block.timestamp);
    }

    function getRoot() public view returns (uint256) {
        return currentRoot;
    }

    // The function the Frontend will use to generate Merkle Paths!
    function getAllLeaves() public view returns (uint256[] memory) {
        return driverLeaves;
    }
}